"""Migracao02

Revision ID: 41f9c4585d1c
Revises: 9f738fa8419c
Create Date: 2022-10-10 06:43:43.153545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f9c4585d1c'
down_revision = '9f738fa8419c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidoMaterial', sa.Column('urn', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidoMaterial', 'urn')
    # ### end Alembic commands ###
