"""Migracao10

Revision ID: 5b7b2bd68945
Revises: 6dc2325b141d
Create Date: 2022-11-26 19:29:37.279628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7b2bd68945'
down_revision = '6dc2325b141d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidoMaterial', sa.Column('nivel00', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidoMaterial', 'nivel00')
    # ### end Alembic commands ###
