"""Migracao01

Revision ID: 9f738fa8419c
Revises: 
Create Date: 2022-10-09 21:32:34.925540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f738fa8419c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidoMaterial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=True),
    sa.Column('unid', sa.String(length=100), nullable=True),
    sa.Column('qtde', sa.Float(), nullable=True),
    sa.Column('mes', sa.String(length=100), nullable=True),
    sa.Column('objectId', sa.String(length=100), nullable=True),
    sa.Column('pedidoGuid', sa.String(length=100), nullable=True),
    sa.Column('pedido', sa.String(length=100), nullable=True),
    sa.Column('nivel01', sa.String(length=100), nullable=True),
    sa.Column('nivel02', sa.String(length=100), nullable=True),
    sa.Column('idElement', sa.Integer(), nullable=True),
    sa.Column('pedidoId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedidoId'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidoMaterial')
    op.drop_table('pedido')
    # ### end Alembic commands ###
