"""Migracao02

Revision ID: da57a143bbe7
Revises: acc6d4fb6ebc
Create Date: 2022-10-13 13:41:38.947982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da57a143bbe7'
down_revision = 'acc6d4fb6ebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PacotesDeEntrega', sa.Column('volume', sa.Float(), nullable=True))
    op.add_column('PacotesDeEntrega', sa.Column('base', sa.Float(), nullable=True))
    op.add_column('PacotesDeEntrega', sa.Column('largura', sa.Float(), nullable=True))
    op.add_column('PacotesDeEntrega', sa.Column('altura', sa.Float(), nullable=True))
    op.add_column('PacotesDeEntrega', sa.Column('formato', sa.String(length=50), nullable=True))
    op.add_column('PacotesDeEntrega', sa.Column('empolamento', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PacotesDeEntrega', 'empolamento')
    op.drop_column('PacotesDeEntrega', 'formato')
    op.drop_column('PacotesDeEntrega', 'altura')
    op.drop_column('PacotesDeEntrega', 'largura')
    op.drop_column('PacotesDeEntrega', 'base')
    op.drop_column('PacotesDeEntrega', 'volume')
    # ### end Alembic commands ###
